# google_client_id: "747870022789-9g6go7a6cvb8hkuqrr0q8ghqun4mmmjr.apps.googleusercontent.com"
# google_client_secret: "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"
database:
  username: ratheesh
  password: root
